import { handleErrors } from "../../../../helpers/haddle-error"

export const DeleteOnsenController = async (req, res) => {
  try {

  } catch (error) {
    return handleErrors(res, error)
  }
}